### ISSUE TITLE
Setting the "DISPLAY" variable

### ISSUE THREAD

**Issue by fhightower** [goropikari/nand2tetris#1]
Thanks for creating and sharing this repo! I am reading the same book and would like to run the tools in docker as you have done. When I follow the instructions in the readme, however, I get this error:

```
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
```

After some research, I noticed you provide a `DISPLAY` variable [here](https://github.com/goropikari/nand2tetris/blob/22fd44225bbfd3a4930173d32f728b49baf88bd1/docker-compose.yml#L7). What should the `DISPLAY` variable be set to? I've tried a number of values and none of them work. I'm going to dig into this further myself, but was wondering if you had any advice.

Thanks!

**Comment by goropikari** [comment]
If your host machine is Linux, `export DISPLAY=:0`  maybe work.
If you use other OS, install X11 client at first and follows its setup instruction.
ref: https://askubuntu.com/questions/432255/what-is-the-display-environment-variable

**Comment by fhightower** [comment]
Great, I'll give those a try. Thank you!

**Comment by fhightower** [comment]
Thanks so much for the help! I was able to get this working (documented [here](https://github.com/fhightower/nand2tetris#usage)).
